[project]
name = "resume"
version = "1.0.0"
description = "Pierre's resume"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "rendercv[full]==2.2", # TODO: update to latest version when https://github.com/rendercv/rendercv/issues/531 is resolved
]
